### PR TITLE
268

### PR DESCRIPTION
**Pull request by simonmittag**

### CODE REVIEW

**Comment by simonmittag** [comment]
@intermernet @MayankGandhe can you please run these changes locally? I'm particularly seeking feedback that the process exit (HIT CTRL+C) works as expected and it doesn't hang!

**Comment by MayankGandhe** [comment]
@simonmittag It is working as expected , checked by pressing CTRL+C with master branch and this branch in this branch message got print `{"level":"fatal","srvId":"ad235e25","pid":35821,"pid":35821,"time":"2022-07-11T15:36:09+05:30","message":"exiting..."}`
Where in case of master branch only exit happend

**Review by MayankGandhe — APPROVED** [review]

**Comment by simonmittag** [comment]
i'll merge this within 24h unless i hear to the contrary from anyone.

**Comment by simonmittag** [comment]
@MayankGandhe also see what happens during config panic now, it should stop printing stack trace

**Pull request merged**
